name: terraform-ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read # This is required for actions/checkout

env:
  TERRAFORM_VERSION: 1.10.0
  TFLINT_VERSION: v0.54.0
  TRIVY_VERSION: v0.58.1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4
      - name: Setup pre-commit
        run: sudo apt-get install -y pre-commit
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}
      # - name: Setup Trivy
      #   run: |
      #     wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
      #     sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          cache: true
          version: ${{ env.TRIVY_VERSION }}
      - name: Setup Terraform Docs
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install terraform-docs
      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --all-files
